### ISSUE TITLE
Trying to support mod manager, get error when checking for version on my mod

### ISSUE THREAD

**Issue by Amnesiac9** [FluffierThanThou/ModManager#54]
I know you're probably very busy, sorry to bother you with this issue, but I'd love to learn how to support your mod manager. It seems to just not work for me :(

Screenshot of the error: https://i.imgur.com/D9KXN0d.png

Here's my Manifest.xml file: 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Manifest>
  <version>1.0.2</version>
  <manifestUri>https://github.com/Amnesiac9/JEM-Animals/blob/master/JEM-Animals/About/Manifest.xml</manifestUri>
  <downloadUri>https://github.com/Amnesiac9/JEM-Animals/releases/tag/1.0.2</downloadUri>
</Manifest>

And my github repository: https://github.com/Amnesiac9/JEM-Animals

What am I doing wrong? :(

**Comment by FluffierThanThou** [comment]
You're using a link to the github page for your mannifest, rather than to the 'raw' manifest file.

If you look at my manifests, you'll see I'm using links like these; `https://cdn.jsdelivr.net/gh/FluffierThanThou/ModManager/About/Manifest.xml`. You can do the same, or google `github raw file link` for other options.

**Comment by Amnesiac9** [comment]
OH ok, I got it working! thank you so much for the reply! 

I'd never linked to files from my github before and I didn't realize my links weren't correct, I tried copying your manifest directly from one of your mods and replacing it with my info but I didn't notice the raw link, and I didn't see any clues in the documentation so I had no idea.

Thanks again!
